FROM python:3.9.4-slim-buster AS build-stage
RUN mkdir -p /opt/tail-agent
WORKDIR /opt/tail-agent
COPY tail-agent/requirements.txt .
RUN pip install -r requirements.txt && pip install pylint
COPY tail-agent/ /opt/tail-agent/
RUN pylint *.py --exit-zero > pylint.log

FROM scratch as export-stage
COPY --from=build-stage /opt/tail-agent/pylint.log .
