FROM python:3.9.4-slim-buster AS build-stage
RUN mkdir -p /opt/tail-agent
WORKDIR /opt/tail-agent
COPY tail-agent/requirements.txt .
RUN pip install -r requirements.txt
COPY tail-agent/ /opt/tail-agent/
RUN pylint *.py --exit-zero > pylint.log
RUN python test_tail_agent.py > unittests.log

FROM scratch as export-stage
COPY --from=build-stage /tmp/tail-agent/pylint.log .
COPY --from=build-stage /tmp/tail-agent/unittests.log .